name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npm run lint:check

      - name: Run format
        run: npm run format:check

      - name: Run build
        run: npm run build
